// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzolaWebAPI.Data;

#nullable disable

namespace NzolaWebAPI.Migrations
{
    [DbContext(typeof(ContextoBDNzola))]
    [Migration("20260621160210_MigNotificacoesRemoveMultipleCascadesOrCyclesOnDelete")]
    partial class MigNotificacoesRemoveMultipleCascadesOrCyclesOnDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NzolaWebAPI.Models.Baze", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoBaze")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizadorId1")
                        .HasColumnType("int");

                    b.HasKey("UtilizadorId", "PublicacaoId");

                    b.HasIndex("UtilizadorId1");

                    b.HasIndex("PublicacaoId", "UtilizadorId")
                        .IsUnique();

                    b.ToTable("tb_Bazes");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComentadorId")
                        .HasColumnType("int");

                    b.Property<string>("ConteudoComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentadorId");

                    b.HasIndex("PublicacaoId");

                    b.ToTable("tb_Comentarios");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.FicheiroConteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoFicheiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("int");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.ToTable("tb_FicheirosConteudo");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrigemId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("tb_Notificacoes", t =>
                        {
                            t.HasCheckConstraint("CK_Notificacoes_Tipo", "Tipo IN ('Baze','Comentario', 'Seguidor')");
                        });
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacaoPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Existencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("QuantidadeBazes")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeComentarios")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("tb_Publicacoes");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Seguidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeguidoId")
                        .HasColumnType("int");

                    b.Property<int>("SeguidorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeguidoId");

                    b.HasIndex("SeguidorId");

                    b.ToTable("tb_Seguidores");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EstadoConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PalavraPasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Privacidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUtilizador")
                        .IsUnique();

                    b.ToTable("tb_Utilizadores", t =>
                        {
                            t.HasCheckConstraint("CK_Utilizadores_Genero", "Genero IN ('Masculino','Feminino')");
                        });
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Baze", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Publicacao", "Publicacao")
                        .WithMany("Bazes")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NzolaWebAPI.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NzolaWebAPI.Models.Utilizador", null)
                        .WithMany("Bazes")
                        .HasForeignKey("UtilizadorId1");

                    b.Navigation("Publicacao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Comentario", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Utilizador", "Utilizador")
                        .WithMany("Comentarios")
                        .HasForeignKey("ComentadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzolaWebAPI.Models.Publicacao", "Publicacao")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.FicheiroConteudo", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Publicacao", "Publicacao")
                        .WithMany("Ficheiros")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Notificacao", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Utilizador", "UtilizadorResponsavel")
                        .WithMany()
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzolaWebAPI.Models.Utilizador", "UtilizadorNotificacao")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilizadorNotificacao");

                    b.Navigation("UtilizadorResponsavel");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Publicacao", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Utilizador", "Utilizador")
                        .WithMany("Publicacoes")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Seguidor", b =>
                {
                    b.HasOne("NzolaWebAPI.Models.Utilizador", "UtilizadorSeguido")
                        .WithMany("Seguidores")
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NzolaWebAPI.Models.Utilizador", "UtilizadorSeguidor")
                        .WithMany("Seguindo")
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilizadorSeguido");

                    b.Navigation("UtilizadorSeguidor");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Publicacao", b =>
                {
                    b.Navigation("Bazes");

                    b.Navigation("Comentarios");

                    b.Navigation("Ficheiros");
                });

            modelBuilder.Entity("NzolaWebAPI.Models.Utilizador", b =>
                {
                    b.Navigation("Bazes");

                    b.Navigation("Comentarios");

                    b.Navigation("Notificacoes");

                    b.Navigation("Publicacoes");

                    b.Navigation("Seguidores");

                    b.Navigation("Seguindo");
                });
#pragma warning restore 612, 618
        }
    }
}
